### ISSUE TITLE
2x2 Block Bottleneck Solution Idea

### ISSUE THREAD

**Issue by torridgristle** [sedthh/pyxelate#17]
I'm having a hard time wrapping my head around what's going on, but it looks like the problem area is just a shitload of 2x2 images going through convolution.

What if it was just one big image? For example, convolution on an image with this kernel:
```
0 0 0
0 0 1
0 0 0
```
should be the same as moving the image over 1 pixel, and convolution on an image with this kernel:
 ```
  0 0 0
-1 0 1
  0 0 0
```
should be the same as duplicating the image, moving one right 1 pixel, moving the other duplicate left 1 pixel and multiplying the values by -1, and adding them together.

If there's an issue with 2x2 blocks overlapping due to the entire image moving, I think you could do like `mod(x - (floor(x / 2) * 2) + offset, 2) + (floor(x / 2) * 2)` on the texture coordinates when in 0 to (width-1) range rather than 0-1, thinking in GLSL at least. It's been a while since I've done GLSL though so please don't take my word for it.

**Comment by sedthh** [comment]
Thank you for these ideas! The new version creates 3x3 tiles in cython (through scikit-image's HOG) and uses the gradients. This solution is now many magnitudes faster.
