### ISSUE TITLE
[Suggestion] Alternatives to hog for faster runtime

### ISSUE THREAD

**Issue by Seon82** [sedthh/pyxelate#19]
The new version of the program runs significantly slower than the previous version (with the speedup provided by #18). A bit of profiling reveals the hog method as the main culprit. 
I've implemented a few alternative algorithms I thought might show similar results, and benchmarked the time necessary to do a fit_transform using these different methods. I feel like the 2x2 sobel could be a pretty solid alternative to hog, what do you think?

*(All benchmarks run with dither="naive", palette=6 and boost=True)*

**There's a small mistake in the labels, 3x3 sobel is in fact 2x2 and vice-versa**

Factor 6
---
![pyxelate_robocop_med](https://user-images.githubusercontent.com/46298009/113921540-6d7b4700-97e6-11eb-9b91-b6830c9e1132.png)

Factor 10
---
![pyxelate_br_small](https://user-images.githubusercontent.com/46298009/113920553-35bfcf80-97e5-11eb-8ccc-e4bc1a35e8f8.png)
Factor 6
---
![pyxelate_br_med](https://user-images.githubusercontent.com/46298009/113920595-42dcbe80-97e5-11eb-943c-219a563de47b.png)
Factor 3
---
![pyxelate_br_large](https://user-images.githubusercontent.com/46298009/113920588-3fe1ce00-97e5-11eb-8872-04a7293a7200.png)

Factor 10
---
![pyxelate_corgi_small](https://user-images.githubusercontent.com/46298009/113920574-3a848380-97e5-11eb-99c8-281c2b186604.png)
Factor 6
---
![pyxelate_corgi_med](https://user-images.githubusercontent.com/46298009/113920563-37899300-97e5-11eb-83b2-05ad79d5cba8.png)

Factor 10
---
![pyxelate_palms_small](https://user-images.githubusercontent.com/46298009/113920583-3e180a80-97e5-11eb-9d49-e253395adfb0.png)

Factor 6
---
![pyxelate_palms_med](https://user-images.githubusercontent.com/46298009/113920725-76b7e400-97e5-11eb-9564-0bb5be00c63d.png)

**Comment by sedthh** [comment]
That's a really good idea. I am happy with the top row so it definitely worths a try!
Could you make examples with 3x3 sobel as well, and images where the edge detector is called multiple times (similarly to depth > 1)?

Thank you in advance!

**Comment by Seon82** [comment]
Just noticed a mistake in the labels for the images above, 2x2 sobel is in fact 3x3 and vice-versa. But there are already some 3x3 sobel examples above. 
Will look into the different depths asap!

**Comment by Seon82** [comment]
Depth 2
---
![br_depth2](https://user-images.githubusercontent.com/46298009/114024265-1f148980-9874-11eb-9fd2-2cb54d4e04de.png)

Depth 3
---
![br_depth3](https://user-images.githubusercontent.com/46298009/114024279-23d93d80-9874-11eb-8a3c-b52be95e5621.png)
![palms_depth3](https://user-images.githubusercontent.com/46298009/114024270-2176e380-9874-11eb-9f50-4914ddcb5fb3.png)

**Comment by sedthh** [comment]
I love it! Could you maybe add both 2x2 and 3x3 as choices to be set s hyperparameters with Pyx() with 3x3 as default? The 3x3 looks better but 2x2 is just so much faster, it will worth the tradeoff for rendering animations later!
`Pyx(sobel=3)`

This is great!
