### ISSUE TITLE
Dithering area inconsistent when running image sequences.

### ISSUE THREAD

**Issue by mbilyanov** [sedthh/pyxelate#29]
Hi,

First of all, what a great tool! This has a great creative potential and I have been using it for a while now.

One issue I'm  having is, with image sequences I get some areas with dithering that are jumping around when run through `pyxelate`. I know it is a difficult problem to solve as the shading of those areas change from frame to frame. I can try and share some test images if you are interested. I wish there was a way to lock the dithering samples?

What I tried, is generating the palette from a single image:
```
pyx = Pyx(upscale=1, factor=2, dither="naive", alpha=0.4, sobel=5, palette=7)
pyx.fit(init_image)
```

`init_image` being a single image out of the whole sequence.

But that did not solve my issues.

**Comment by sedthh** [comment]
Hi, 

yes there are indeed multiple issues when using the current version of Pyxelate with a sequence of images. I have solved most of them in the previous version but did not have the time to reimplement them for the current one. 

Sequences are often flickering (small changes that are often not even noticable by the human eye can cause the script to create artifacts) which gets exponentially worse when dithering is applied. As a solution, the original algorithm was only applied on areas where an image would change significantly, leaving the rest of the image unchanged. 

I was able to achieve the following with the old version:
https://drive.google.com/file/d/1P1iHpsQpWx1vlZR8WekQnoRofwrqItT5/view?usp=sharing

I don't know if anyone actually used this video feature back then so I made it a low priority.

**Comment by sedthh** [comment]
Nevermind I rewrote the functions that calculate the differences between images to reduce flicker.

Can you take a look at: https://github.com/sedthh/pyxelate/tree/video-support

You can do the following with the 2 new generators in `vid.py`:

```python
import os
from skimage import io
from pyxelate import Pyx, Pal, images_to_parts, parts_to_images

# get all images
images = []
for file in os.listdir("where_my_images_are/"):
    image = io.imread(file)
    images.append(image)
    
# generate a new image sequence based on differences between them
new_images, new_keys = [], []
for i, (image, key) in enumerate(images_to_parts(images)):
    if key:  # update palette at keyframes, this can be 'if key == 0' instead
        pyx = Pyx(factor=5, upscale=5, palette=8, dither="naive").fit(image)
    # run the algorithm on the difference only
    image = pyx.transform(image)
    # save the pyxelated image part for later
    new_images.append(image)
    new_keys.append(key)

# put the pyxelated parts back together
for i, image in enumerate(parts_to_images(new_images, new_keys)):
    io.imsave(f"converted_images_with_reduced_flicker/img_{i}.png", image)
```

**Comment by sedthh** [comment]
Please check  https://github.com/sedthh/pyxelate/tree/video-support branch

**Comment by mbilyanov** [comment]
Thank you. Looks like a good solution. Will test further.
