### ISSUE TITLE
This isnt pixel art filter but color limiter filter, pretty average one 

### ISSUE THREAD

**Issue by 2blackbar** [sedthh/pyxelate#35]
The name is misleading, pixel art is not any image with 8 colours, its actually art made in a way that it appears to have depth ,shadows and highlights using pixels to minimize color banding, and in your case its full on 100% color banding.
Maybe aim for 16 colours or try to use dither patterns common in pixel art to make it look better.
I know it is not simple color limiter but the result still asthetically looks like color limiter.

**Comment by sedthh** [comment]
Thank you, please add this to the README.md in all caps instead.
