### ISSUE TITLE
Dithering always on when using pyx.py

### ISSUE THREAD

**Issue by wporter82** [sedthh/pyxelate#4]
No matter what is passed in via the command line, the parsed argument always evaluates to true. This means you can't disable dithering.

**Comment by sedthh** [comment]
Thanks for letting me know. 
Turns out the argument parser disregards the tpye=bool declaration and always interprets the value as a string, which in turn would always result True. It is now fixed, sorry for the wait.

**Comment by ElliotWood** [comment]
Same thing happens for '-r', '--regenerate_palette'

**Comment by sedthh** [comment]
Thank you for pointing this out, I've issued a fix for it!
